CREATE OR REPLACE FUNCTION Dipendente_uppercase() RETURNS TRIGGER
LANGUAGE PLPGSQL 
AS $$
BEGIN
  NEW.CF = UPPER(NEW.CF);  
  RETURN NEW;
END;
$$;
  

CREATE TRIGGER CF_uppercase_Dipendente
  BEFORE INSERT OR UPDATE
  ON Dipendente
  FOR EACH ROW
  EXECUTE PROCEDURE Dipendente_uppercase();