CREATE OR REPLACE FUNCTION Abilità_uppercase() RETURNS TRIGGER
LANGUAGE PLPGSQL 
AS $$
BEGIN
  NEW.CF = UPPER(NEW.CF);  
  RETURN NEW;
END;
$$;
  

CREATE TRIGGER CF_uppercase_Abilità
  BEFORE INSERT OR UPDATE
  ON Abilità
  FOR EACH ROW
  EXECUTE PROCEDURE Abilità_uppercase();